import type { Config } from "tailwindcss";

// Tokens portados de base/DESIGN.md ("Serene Heritage")
const config: Config = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        surface: "#fafaf4",
        "surface-dim": "#dadad5",
        "surface-bright": "#fafaf4",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f4f4ee",
        "surface-container": "#eeeee9",
        "surface-container-high": "#e8e8e3",
        "surface-container-highest": "#e3e3de",
        "on-surface": "#1a1c19",
        "on-surface-variant": "#404940",
        "inverse-surface": "#2f312e",
        "inverse-on-surface": "#f1f1ec",
        outline: "#717970",
        "outline-variant": "#c0c9be",
        "surface-tint": "#2d6a3e",
        primary: "#115128",
        "on-primary": "#ffffff",
        "primary-container": "#2d6a3e",
        "on-primary-container": "#a6e8b0",
        "inverse-primary": "#95d59f",
        secondary: "#5f5f57",
        "on-secondary": "#ffffff",
        "secondary-container": "#e2e0d6",
        "on-secondary-container": "#64635b",
        tertiary: "#524528",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#6b5c3e",
        "on-tertiary-container": "#ead5af",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#b0f2ba",
        "primary-fixed-dim": "#95d59f",
        "on-primary-fixed": "#00210b",
        "on-primary-fixed-variant": "#115228",
        "secondary-fixed": "#e5e2d9",
        "secondary-fixed-dim": "#c9c6bd",
        "on-secondary-fixed": "#1c1c16",
        "on-secondary-fixed-variant": "#484740",
        "tertiary-fixed": "#f5e0ba",
        "tertiary-fixed-dim": "#d8c49f",
        "on-tertiary-fixed": "#241a03",
        "on-tertiary-fixed-variant": "#534529",
        background: "#fafaf4",
        "on-background": "#1a1c19",
        "surface-variant": "#e3e3de",
      },
      fontFamily: {
        "display-lg": ["var(--font-bodoni)", "serif"],
        "headline-lg": ["var(--font-bodoni)", "serif"],
        "headline-md": ["var(--font-bodoni)", "serif"],
        "headline-sm": ["var(--font-bodoni)", "serif"],
        "body-lg": ["var(--font-jakarta)", "sans-serif"],
        "body-md": ["var(--font-jakarta)", "sans-serif"],
        "label-lg": ["var(--font-jakarta)", "sans-serif"],
        "label-sm": ["var(--font-jakarta)", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["64px", { lineHeight: "72px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg": ["48px", { lineHeight: "56px", fontWeight: "500" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "500" }],
        "headline-sm": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
      },
      borderRadius: {
        sm: "0.125rem",
        DEFAULT: "0.25rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
      },
      spacing: {
        unit: "8px",
        "container-max": "1280px",
        gutter: "24px",
        "margin-mobile": "20px",
        "margin-desktop": "64px",
        "section-gap": "120px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
    },
  },
  plugins: [],
};

export default config;
